apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-c5xt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-refg-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-c5xt@sha256:b7d647446f028d22a7238b704171cf732767ab3f793c351c8b6e34d9f382bbe6
        name: my-nodejs
        resources: {}
status: {}
